# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Projects
  #   url: '/project'
  #   weight: 30
  - name: Posts
    url: '/post'
    weight: 20
  # - name: Publications
  #   url: '/publication'
  #   weight: 50
  # - name: Teaching
  #   url: courses/
  #   weight: 60
  # - name: Contact
  #   url: '#contact'
  #   weight: 70
